name: Github Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: treeform/setup-nim-action@v6
      - run: nim check src/webby.nim
      - run: nim check tests/tests.nim
      - run: nim r tests/tests.nim
